version: '3'
services:
  ko-scraper:
    build: .
    container_name: knight-online-price-scraper
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://redis:6379?family=0

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
